language: go

before_install:
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update
  - sudo apt-get install -y solc
after_success:
  - bash <(curl -s https://codecov.io/bash)
go:
  - "1.10.x"

