coverage:
  status:
    patch:
      default:
        threshold: 0.1%
  ignore:
  - "internal/kldkafka/mock_sarama" # Generated mock
  - "internal/kldauth/kldauthtest" # Mock
  - "cmd/plugins.go" # Not testable with UTs
