name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'ethconnect'
      - uses: actions/checkout@v2
        with:
          repository: kaleido-io/ethbinding
          path: 'ethbinding'
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install solc
        run: |
          sudo curl -Lo /usr/local/bin/solc https://github.com/ethereum/solidity/releases/download/v0.7.6/solc-static-linux
          sudo chmod 755 /usr/local/bin/solc

      - name: Build and Test
        env:
          TEST_DEBUG_FLAGS: -v
        run: cd ethconnect && make

      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
